/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import modelo.Cliente;
import modelo.ArriendoCuota;
import modelo.CuotaArriendo;

/**
 *
 * @author xavie
 */
public class VistaArriendosPagar extends javax.swing.JPanel implements InterfazArriendosPagar {

    /**
     * Creates new form VistaArriendosPagar
     */
    public VistaArriendosPagar() {
        initComponents();
        setLstCuotasPorPagar(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        ddlCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstArriendosDelCliente = new javax.swing.JList<>();
        btnBuscar = new javax.swing.JButton();
        btnVerCuotas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCuotasPorPagar = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnPagarCuotas = new javax.swing.JButton();

        jLabel1.setText("Pagar Cuotas Arriendos");

        btnVolver.setText("Volver");

        ddlCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lstArriendosDelCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstArriendosDelCliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstArriendosDelCliente);

        btnBuscar.setText("Buscar arriendos del cliente");

        btnVerCuotas.setText("Mostrar pagos arriendos seleccionado >>");

        lstCuotasPorPagar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstCuotasPorPagar);

        jLabel2.setText("Núm. - Valor - Pagada");

        btnPagarCuotas.setText("Pagar seleccionadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerCuotas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ddlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnPagarCuotas)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ddlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(btnVerCuotas))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPagarCuotas)
                        .addGap(7, 7, 7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPagarCuotas;
    private javax.swing.JButton btnVerCuotas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> ddlCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstArriendosDelCliente;
    private javax.swing.JList<String> lstCuotasPorPagar;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getPanel() {
        return this;
    }
    
    @Override
    public void registrarEscuchador(ActionListener escuchador){
        this.btnVolver.addActionListener(escuchador);
        this.btnVolver.setActionCommand(VOLVER);
        this.btnBuscar.addActionListener(escuchador);
        this.btnBuscar.setActionCommand(BUSCAR);
        this.btnVerCuotas.addActionListener(escuchador);
        this.btnVerCuotas.setActionCommand(BUSCAR_CUOTAS);
    }
    
    @Override
    public int mostrarMensaje(int tipoMensaje, String msj){
        String strTitulo = "Arriendo con cuotas";
        int retorno = 0;
        switch (tipoMensaje){
            case 1: //Solo informativo
                JOptionPane.showMessageDialog(this, msj, strTitulo, JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2: //Si se desea eliminar
                retorno = JOptionPane.showConfirmDialog(this, msj, strTitulo, JOptionPane.OK_CANCEL_OPTION);
                break;
            case 3: //Si hay un error
                JOptionPane.showMessageDialog(this, msj, strTitulo, JOptionPane.ERROR_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Acción no implementada", strTitulo, JOptionPane.INFORMATION_MESSAGE);
        }
        return retorno;
    }
    
    @Override
    public String getClienteSeleccionado(){
        if (this.ddlCliente.getSelectedIndex() == 0){
            
        }
        return this.ddlCliente.getSelectedItem().toString();
    }
    
    @Override
    public void setDllCliente(ArrayList<Cliente> clientes){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel();
        this.ddlCliente.setModel(model);
        
        model.addElement(new String("--Seleccione Cliente--"));
        for(int i = 0; i < clientes.size(); i++) {
            Cliente cliente = clientes.get(i);

            model.addElement(cliente.toString());
        }//for
    }
    
    @Override
    public void setLstArriendosDelCliente(ArrayList<ArriendoCuota> arriendos){
        DefaultListModel<String> model = new DefaultListModel();
        this.lstArriendosDelCliente.setModel(model);
            if (arriendos != null && !arriendos.isEmpty()){
                for(int i = 0; i < arriendos.size(); i++) {
                ArriendoCuota arriendo = arriendos.get(i);
                model.addElement(arriendo.getVehiculo().getPatente() + " - " + arriendo.getVehiculo().getMarca() + "/" + arriendo.getVehiculo().getModelo());    
            }//for
        }//if
    }
    
    @Override
    public String getArriendoSeleccionado(){
        return this.lstArriendosDelCliente.getSelectedValue();
    }
    
    @Override
    public void setLstCuotasPorPagar(ArrayList<CuotaArriendo> cuotasArriendos){
        DefaultListModel<String> model = new DefaultListModel();
        this.lstCuotasPorPagar.setModel(model);
            if (cuotasArriendos != null && !cuotasArriendos.isEmpty()){
                for(int i = 0; i < cuotasArriendos.size(); i++) {
                CuotaArriendo cuotasDelCliente = cuotasArriendos.get(i);
                model.addElement(String.valueOf(cuotasDelCliente.getNumCuota()) + " - " + String.valueOf(cuotasDelCliente.getValorCouta()) + " - " + (cuotasDelCliente.isPagada() ? "Sí" : "No"));
            }//for
        }//if
    }
    
    @Override
    public void vaciarCosas(){
        this.setLstArriendosDelCliente(null);
        this.setLstCuotasPorPagar(null);
    }
    
}
